name: zsim
channels:
  - conda-forge
dependencies:
  - statsmodels=0.13.2
  - arch-py=5.5.0
  - scikit-learn=0.23.2
  - pandas=1.3.5
  - scipy=1.7.3
  - astral=2.2
  - plotly=5.6.0
  - ipykernel=6.9.1
  - xarray=2022.6.0
  - matplotlib=3.5.0
  - netcdf4=1.6.2
  - seaborn=0.11.2
